# golangci-lint configuration for hypermcp
# See https://golangci-lint.run/usage/configuration/ for full options

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  
  enable:
    # Additional recommended linters
    - bodyclose     # Check HTTP response body is closed
    - dupl          # Code duplication detection
    - gocognit      # Cognitive complexity
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Cyclomatic complexity
    - gosec         # Security problems
    - misspell      # Spelling mistakes
    - revive        # Golint replacement
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - whitespace    # Whitespace issues

  disable:
    - exhaustive    # Too strict for switch statements
    - exhaustruct   # Too strict for struct initialization
    - gochecknoglobals # Globals are sometimes necessary
    - gochecknoinits # Init functions have valid uses
    - godox         # Allow TODOs in code
    - wrapcheck     # Too strict for error wrapping

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Disabled: test structs are not performance-critical
      settings:
        shadow:
          strict: true

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    revive:
      rules:
        - name: exported
          disabled: false
          arguments:
            - "checkPrivateReceivers"
            - "disableStutteringCheck"

    gosec:
      excludes:
        - G104 # Audit use of errors, already covered by errcheck
        - G307 # Defer error handling is checked elsewhere

formatters:
  enable:
    - gofmt         # Check code formatting
    - goimports     # Check import ordering

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    
    rules:
      # Exclude examples directory - these are for demonstration purposes
      - path: examples/
        linters:
          - errcheck
          - gosec
          - govet
          - gofmt
      
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - gocyclo
          - gocognit
        
      # Exclude specific staticcheck messages
      - linters:
          - staticcheck
        text: "SA1019:" # Ignore deprecation warnings

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - file
